version: "3.9"

services:
  ukenzie:
    container_name: ukenzie_projeto
    image: ukenzie
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
      - DB=defaultdb
      - DB_PASSWORD=123456
      - DB_PORT=5432
  db:
    container_name: db
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=defaultdb
